basePath: /api/v1
definitions:
  entity.User:
    properties:
      email:
        type: string
      uuid:
        type: string
    type: object
  v1.loginPayload:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: dimk0z@yandex.ru
    name: Kuznetsov Dmitriy
    url: https://github.com/dimk00z
  description: Gophkeeper project
  title: Gophkeeper Server
  version: 1.0.0
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: add new user
      operationId: register
      parameters:
      - description: Sing up new user
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.loginPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Register user
      tags:
      - Auth
  /health:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Show the status of server.
      tags:
      - health
swagger: "2.0"
